# WARNING! This file is not managed by Ansible and should not contain any usage of its features.
---
cmf: drupal
core: 8
project: drangular
site_url: https://drangular.dev
tmproot: /tmp
webroot: /var/www
profile: pp
settings: sites/default/settings.php
filesystem: sites/default/files
composer_packages:
  drush/drush: 8.*
  squizlabs/php_codesniffer: 2.*
vm:
  ip: 192.168.56.132
  ports: [80, 3306, 4444]
  folders:
    - source: ./
      target: /var/www
      # Not supported on Cygwin.
      nfs:
        # If you're using guest machine more often than host for manipulating
        # by big file data, then you should configure NFS over TCP connection
        # to prevent hangs. Generally it's not recommended and we suggest to
        # use mounted folder on your host. But you may choose.
        # https://github.com/mitchellh/vagrant/issues/2304
        udp: true
        # Do not change this option if don't understand what you're doing!
        version: 3
  virtualbox:
    modifyvm:
      cpus: 1
      memory: 2048
      natdnshostresolver1: "on"
